# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderqueue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10orderqueue.proto\x12\norderqueue\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x05Order\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x19\n\x11\x66ull_request_data\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t\"7\n\x12OrderQueueResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x87\x01\n\x11OrderQueueService\x12<\n\x07\x45nqueue\x12\x11.orderqueue.Order\x1a\x1e.orderqueue.OrderQueueResponse\x12\x34\n\x07\x44\x65queue\x12\x16.google.protobuf.Empty\x1a\x11.orderqueue.Orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderqueue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=61
  _globals['_ORDER']._serialized_end=128
  _globals['_ORDERQUEUERESPONSE']._serialized_start=130
  _globals['_ORDERQUEUERESPONSE']._serialized_end=185
  _globals['_ORDERQUEUESERVICE']._serialized_start=188
  _globals['_ORDERQUEUESERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
