# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fraud_detection_pb2 as fraud__detection__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitFraudDetection = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/InitFraudDetection',
                request_serializer=fraud__detection__pb2.FraudDetectionData.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateVectorClock = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/UpdateVectorClock',
                request_serializer=fraud__detection__pb2.VectorClockStatus.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteCompletedOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/DeleteCompletedOrder',
                request_serializer=fraud__detection__pb2.VectorClockStatus.SerializeToString,
                response_deserializer=fraud__detection__pb2.DeletionResponse.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitFraudDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVectorClock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCompletedOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitFraudDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.InitFraudDetection,
                    request_deserializer=fraud__detection__pb2.FraudDetectionData.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateVectorClock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVectorClock,
                    request_deserializer=fraud__detection__pb2.VectorClockStatus.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteCompletedOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCompletedOrder,
                    request_deserializer=fraud__detection__pb2.VectorClockStatus.FromString,
                    response_serializer=fraud__detection__pb2.DeletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitFraudDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/InitFraudDetection',
            fraud__detection__pb2.FraudDetectionData.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVectorClock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/UpdateVectorClock',
            fraud__detection__pb2.VectorClockStatus.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCompletedOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/DeleteCompletedOrder',
            fraud__detection__pb2.VectorClockStatus.SerializeToString,
            fraud__detection__pb2.DeletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
