# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\x1a\x1bgoogle/protobuf/empty.proto\"6\n\tOrderData\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\x19\n\x11\x66ull_request_data\x18\x02 \x01(\t\"O\n\x12\x46raudDetectionData\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12(\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1a.fraud_detection.OrderData\">\n\x15\x46raudDetectionRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x14\n\x0cvector_clock\x18\x02 \x03(\x05\"Q\n\x16\x46raudDetectionResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x14\n\x0cvector_clock\x18\x02 \x03(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\xcd\x01\n\x15\x46raudDetectionService\x12Q\n\x12InitFraudDetection\x12#.fraud_detection.FraudDetectionData\x1a\x16.google.protobuf.Empty\x12\x61\n\x0e\x46raudDetection\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERDATA']._serialized_start=71
  _globals['_ORDERDATA']._serialized_end=125
  _globals['_FRAUDDETECTIONDATA']._serialized_start=127
  _globals['_FRAUDDETECTIONDATA']._serialized_end=206
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=208
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=270
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=272
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=353
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=356
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
