# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0f\x45lectionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\x10\x45lectionResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\"\x1f\n\nLeaderInfo\x12\x11\n\tleader_id\x18\x01 \x01(\x05\" \n\x0cPingResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x32\xaf\x02\n\x14OrderExecutorService\x12R\n\rStartElection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12\x44\n\x0e\x41nnounceLeader\x12\x1a.order_executor.LeaderInfo\x1a\x16.google.protobuf.Empty\x12<\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1c.order_executor.PingResponse\x12?\n\rExecuteOrders\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ELECTIONREQUEST']._serialized_start=69
  _globals['_ELECTIONREQUEST']._serialized_end=98
  _globals['_ELECTIONRESPONSE']._serialized_start=100
  _globals['_ELECTIONRESPONSE']._serialized_end=138
  _globals['_LEADERINFO']._serialized_start=140
  _globals['_LEADERINFO']._serialized_end=171
  _globals['_PINGRESPONSE']._serialized_start=173
  _globals['_PINGRESPONSE']._serialized_end=205
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=208
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
