{
 "title": "BookstoreDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Gauge: Currently Processing Orders",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_currently_processed_orders_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gauge: Currently Enqueued Orders",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orderqueue_currently_enqueued_orders_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Counter: Total Rejected Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "orders_rejected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Counter: Total Order Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "orders_total", "legendFormat": "__auto" },
    { "expr": "orders_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Updown counter: Number of Orders Waiting in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "queue_queued_orders", "legendFormat": "Number of orders in queue" }
   ]
  },
  {
   "title": "Updown counter: Number of Orders Being Currently Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "orchestrator_currently_processed_orders",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram: Orchestrator Processing Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_processing_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram: Queue Wait Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queue_waiting_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Span: Orchestrator",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "9ef6f541", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "orchestrator" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  }
 ]
}